import os
from uuid import uuid4

from langchain.docstore.document import Document

data = [
    {
        "type_id": 1,
        "question_id": 16,
        "question": "Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire",
        "responses": [
            "46. Sciences familiales",
            "45. Sc. De l'environnement",
            "52. Technologie",
            "18. Droit",
            "22. Éducation coopérative",
            "36. IPEJ",
            "49. Sciences sociales",
            "10. Biologie",
            "29. Français",
            "39. Mécanique des moteurs",
            "35. Intro. Science de l'info.",
            "48. Sciences humaines",
            "50. Systèmes mécaniques",
            "14. Chimie",
            "42. Physique",
            "47. Sciences générales",
            "37. Leadership",
            "54. Trait. De l'information",
            "3. Alimentation et nutrition",
            "44. Saisie sur clavier",
            "12. Braille Nameth",
            "20. Éduc. Du consommateur",
            "5. Anglais",
            "53. Textiles et habillement",
            "9. Atelier de métaux",
            "2. Agriculture",
            "40. Menuiserie",
            "19. Économie",
            "6. Art dramatique",
            "33. Informatique appliqué",
            "1. Act.Quot.(handicap vis.)",
            "43. Relations familiales",
            "11. Braille abrégé",
            "13. Charpenterie",
            "30. Géographie",
            "28. Formation personnelle",
            "17. Développement humain",
            "15. Comptabilité",
            "27. Espagnol",
            "51. Techno. (handicap visuel)",
            "26. Entreprenariat",
            "7. Arts Industriels",
            "34. Initiation au travail",
            "41. Musique",
            "25. Électronique",
            "24. Électricité",
            "31. Histoire",
            "32. Informatique",
            "38. Mathématiques",
            "8. Arts visuels",
            "16. Dessin industriel",
            "4. Allemand",
            "21. Éducation aux valeur",
            "23. Éducation physique",
        ],
    },
    {
        "type_id": 1,
        "question_id": 17,
        "question": "Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?",
        "responses": [
            "Satisfait/e",
            "Très insatisfait/e",
            "Insatisfait/e",
            "Non répondu",
            "Très satisfait/e",
        ],
    },
    {
        "type_id": 1,
        "question_id": 18,
        "question": "Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?",
        "responses": [
            "Satisfait/e",
            "Très insatisfait/e",
            "Insatisfait/e",
            "Non répondu",
            "Très satisfait/e",
        ],
    },
    {
        "type_id": 1,
        "question_id": 19,
        "question": "Que prévoyez-vous faire en septembre prochain ?",
        "responses": [
            "Marché du travail",
            "Année sabbatique",
            "Programmes jeunesse",
            "Ligne de hockey",
            "Formation professionnelle",
            "Retours aux études secondaires",
            "Voyage pour Missionnaire",
            "Cégep",
            "Études collégiales",
            "Ne sais pas",
            "Non répondu",
            "Voyager",
            "Études universitaires",
            "Écoles des pêches",
            "Indécis du domaine souhaiter",
            "Programme jeunesse",
            "Cours se donne seulement aux 2 ans",
            "Pas assez de bonnes notes",
            "Cours par correspondance",
            "Armée",
        ],
    },
    {
        "type_id": 1,
        "question_id": 20,
        "question": "Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?",
        "responses": [
            "Mathématiques, informatique et sciences physiques",
            "Sciences agricoles et biologiques et services de la nutrition et de l’alimentation",
            "Professions de la santé et technologies connexes",
            "Commerce, gestion et administration des affaires",
            "Beaux-arts et arts appliqués",
            "Lettres, sciences humaines et disciplines connexes",
            "Enseignement, loisirs et orientation",
            "Sciences sociales et disciplines connexes",
            "Génie et sciences appliquées",
            "Sans spécialisation",
            "Non répondu",
            "Techniques et métiers des sciences appliquées",
        ],
    },
    {
        "type_id": 1,
        "question_id": 21,
        "question": "Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?",
        "responses": [
            "Pas utilisés",
            "Peu",
            "Bien",
            "Pas du tout",
            "Très bien",
            "Non répondu",
        ],
    },
    {
        "type_id": 1,
        "question_id": 22,
        "question": "À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?",
        "responses": ["Non", "Non répondu", "Je ne sais pas", "Oui"],
    },
    {
        "type_id": 1,
        "question_id": 23,
        "question": "Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?",
        "responses": [
            "4. Charlotte (N.-B.)",
            "19. Nouvelle-Écosse",
            "20. Ontario",
            "26. Yukon",
            "35. Canada",
            "17. IPE",
            "31. Autre",
            "11. Restigouche (N.-B.)",
            "24. Alberta",
            "27. Territoire du Nord-Ouest",
            "16. York (N.-B.)",
            "33. Autre(s) province(s)",
            "23. Saskatchewan",
            "6. Kent (N.-B.)",
            "1. Dans la Péninsule acadienne",
            "32. Nouveau-Brunswick",
            "12. Sunbury (N.-B.)",
            "2. Albert (N.-B.)",
            "10. Queens (N.-B.)",
            "21. Québec",
            "18. Terre-Neuve",
            "3. Carleton (N.-B.)",
            "9. Northumberland (N.-B.)",
            "7. Kings (N.-B.)",
            "30. Angleterre",
            "29. France",
            "8. Madawaska (N.-B.)",
            "14. Victoria (N.-B.)",
            "28. État-Unis",
            "13. Saint-Jean (N.-B.)",
            "22. Manitoba",
            "5. Gloucester (N.-B.)",
            "15 Westorland (N.-B.)",
            "34. Autre(s) pays",
            "25. Colombie-Britanique",
        ],
    },
    {
        "type_id": 1,
        "question_id": 24,
        "question": "Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?",
        "responses": [
            "Université de Sherbrooke",
            "University Mount Allison",
            "Notre-Dame-de-Foy",
            "Université Western",
            "Recording Arts Canada",
            "Oulton College",
            "CITÉ COLLÉGIALE",
            "Eastern College",
            "MEDES Institutes",
            "SALON CAROUSSEL",
            "Université de Moncton - campus Moncton",
            "NDI",
            "Université Laval",
            "Académie de Police (Régina)",
            "CCNB (PA)",
            "UNIVERSITE LAVAL",
            "NBCC Miramichi Campus",
            "CCNB MIRAMICHI",
            "Nav Canada",
            "College de la Garde Cotière Canadienne",
            "Université St-Francis Xavier",
            "ESSENCE INSTITUT",
            "UNIVERSITÉ DE MONTRÉAL",
            "École de coiffure Rose-Hélène",
            "Autre",
            "CCNB Moncton",
            "OULTON COLLEGE",
            "2. Bourses étudiantes",
            "4. Économie personnelle",
            "ACADEMY OF LEARNING MIRAMICHI",
            "Brenda dog grooming",
            "Académie paramédicale de lAtlantique",
            "Universdad de Boenos",
            "NAIT",
            "1. Prêt étudiant",
            "UNIVERSITÉ D'OTTAWA",
            "UNIVERSITÉ STE-ANNE",
            "CCNB (Bathurst)",
            "ÉCOLE DES PÊCHES",
            "THE ART INSTITUTE OF TORONTO",
            "6. Autre",
            "MEMORIAL UNIVERSITY",
            "St-Thomas University",
            "Cégep",
            "Université d Acadia",
            "COLLÈGE LASALLE",
            "École nationale opération de machinerie lourde",
            "Université de Guelph",
            "Mount Allison",
            "Académie La Coupe Plus",
            "CCNB (Campbelton)",
            "Université de Moncton - campus Edmunston",
            "Université McGill",
            "COLLÈGE BORÉAL",
            "College de technologie forestiere des Maritimes",
            "COLLÈGE MILITAIRE ROYAL DU CANADA",
            "CCNB Campbellton-Cours distance",
            "Centre de formation de la Haute-Gaspésie",
            "Institut humanitaire",
            "University of Mobile",
            "Le Collège Atlantic de Massage thérapeutique",
            "centre de formation professionnelle , Trois Rivières. qc",
            "CRIF",
            "Université de Montréal",
            "CCNB (Edmunston)",
            "CCNB (Autre)",
            "CITE COLLÉGIALE",
            "Dalhousie  University",
            "Université St Mary's",
            "ECOLE DES MÉTIERS DE L'INDUSTRIE DE LA CONSTRUCTION",
            "INST. TECH.D'AGROALIMENTAIRE",
            "Université de l'Ile du Prince Edouard",
            "3. Contribution des parents",
            "Campus Notre Dame de Foy",
            "NBCC MONCTON",
            "UCAM",
            "Université de Moncton - campus Bathurst",
            "Université du Nouveau-Brunswick",
            "Université de Concardia",
            "CCNB Fredericton",
            "Collège Acadie, Université Ste-Anne",
            "Amor Esthétique",
            "Université Hearst",
            "Maritime College of forest technololgy",
            "ÉCOLE DE COIFFURE DE LA PÉNINSULE",
            "UNIVERSITÉ LAURENTIENNE",
            "UNIVERSITÉ DE MONCTON(CAMPUS DE SHIPPAGAN ET MONCTON)",
            "École National du Théatre du Canada",
            "Da Vinci College",
            "Cégep de Ste Foy",
            "Université de Moncton - campus Shippagan",
            "Université de Toronto, campus St-George",
            "Institut Maritime du Québec",
            "JON RAYMOND",
            "MEDES",
            "Université du Québec",
            "Collège Atlantique de massages thérapeutique",
            "CEGEP DE LAPOCATIÈRE",
            "Amoura Esthetic",
            "5. Travail à temps partiel",
            "Non répondu",
            "CCNB (Dieppe)",
            "St Thomas University",
            "Université du Canadienne",
            "BRENDA'S ACADEMY OF PROFESSIONNAL DOG GROOMING",
            "Holland College",
            "Université de Dalhousie",
            "NBCC",
            "Université libre de Bruxelles",
            "Medavie HealtEd",
            "Complexe Capital Hélicoptère",
            "NBCC Monction",
            "Bathurst Hair academy",
            "Collège Merici",
            "UNB",
            "Cégep de Rimouski",
        ],
    },
    {
        "type_id": 1,
        "question_id": 25,
        "question": "Durant vos études postsecondaires, quelles seront vos sources de financement ?",
        "responses": [
            "3. Contribution des parents",
            "2. Bourses étudiantes",
            "4. Économie personnelle",
            "1. Prêt étudiant",
            "5. Travail à temps partiel",
            "6. Autre",
        ],
    },
    {
        "type_id": 1,
        "question_id": 26,
        "question": "Quel moyen de transport local pensez-vous utiliser le plus régulièrement pendant votre première année d'études ?",
        "responses": [
            "11. Covoiturage",
            "10. Taxi",
            "7. Voiture frère/sœur",
            "3. Voiture de mes parents",
            "1. À pied",
            "8. Transport en commun",
            "2. Ma propre voiture/motocyclette",
            "6. Métro",
            "5. Autobus",
            "12. Autre",
            "9. Bicyclette",
            "6. Autre",
            "4. Voiture d'un ami/e ami/e",
        ],
    },
    {
        "type_id": 1,
        "question_id": 27,
        "question": "Quelle est la raison pour laquelle vous ne prévoyez pas poursuivre des études postsecondaire ?",
        "responses": [
            "Accès au marché du travail",
            "Peur de ne pas réussir",
            "Cours non disponible",
            "Aucune idée du domaine à choisir",
            "Manque d’intérêt pour les études/formation",
            "Je travaille ou prévois travailler",
            "Autre",
            "Prendre un an",
            "Armée",
            "Problèmes monétaires",
            "Non répondu",
        ],
    },
    {
        "type_id": 1,
        "question_id": 28,
        "question": "Depuis septembre dernier, avez-vous occupé un emploi rénuméré ?",
        "responses": [
            "5. Autres",
            "1. Non",
            "4. à l'occasion (ex. 1-2 fois par semaine)",
            "2. Temps partiel fin de semaine",
            "3. Temps partiel à la semaine",
        ],
    },
    {
        "type_id": 1,
        "question_id": 29,
        "question": "Est-ce que le fait de terminer votre 12e année est important pour vous ?",
        "responses": [
            "Important",
            "Peu important",
            "Pas du tout important",
            "Très important",
            "Non répondu",
        ],
    },
    {
        "type_id": 1,
        "question_id": 30,
        "question": "En général, quels sont vos résultats scolaires en 10e 11e et 12e année ?",
        "responses": [
            "de 81 % à 94 %",
            "de 56 % à 65 %",
            "de 95 % à 100 %",
            "moins de 55 %",
            "de 66 % à 80 %",
            "Non répondu",
        ],
    },
    {
        "type_id": 1,
        "question_id": 31,
        "question": "En général, vos cours sont de quel niveau scolaire ?",
        "responses": [
            "Adaptation scolaire",
            "PCE",
            "Régulier",
            "Compétences essentielles",
            "Choix",
            "Non répondu",
            "Modifié",
        ],
    },
    {
        "type_id": 1,
        "question_id": 32,
        "question": "En général, êtes-vous satisfait/e de vos résultats scolaires ?",
        "responses": [
            "Satisfait/e",
            "Très insatisfait/e",
            "Insatisfait/e",
            "Non répondu",
            "Très satisfait/e",
        ],
    },
    {
        "type_id": 2,
        "question_id": 45,
        "question": "Depuis combien d'années demeurez-vous à l'extérieur de la Péninsule acadienne ?",
        "responses": [
            "moins d'un an",
            "Deux ans",
            "Un an",
            "Trois ans",
            "Plus de quatre",
            "Non répondu",
            "Quatre ans",
        ],
    },
    {
        "type_id": 2,
        "question_id": 46,
        "question": "Pour quelle raison avez-vous quitté la Péninsule acadienne ?",
        "responses": ["Travail", "Non répondu", "Étude", "Autre"],
    },
    {
        "type_id": 2,
        "question_id": 47,
        "question": "Avez-vous l'intention de vous établir dans la Péninsule acadienne au cours des cinq prochaines années ?",
        "responses": ["Non répondu", "Non", "Ne sais pas", "Oui"],
    },
    {
        "type_id": 2,
        "question_id": 48,
        "question": "Quel est votre niveau d'éducation le plus élevé ?",
        "responses": [
            "Formation personnelle",
            "Secondaire (12 ième année)",
            "Secondaire",
            "Secondaire non-complété",
            "DEG non-complété",
            "Universitaire (baccalauréat)",
            "non répondu",
            "Formation professionnelle",
            "Universitaire (Doctorat)",
            "Non répondu",
            "Collégial",
            "Universitaire (Maîtrise)",
            "DESPA complété",
            "DESPA non complété",
            "Universitaire (Baccalauréat)",
            "DESPA Complété",
            "DEG complété",
            "Secondaire (12 ième complété)",
            "Autre",
        ],
    },
    {
        "type_id": 2,
        "question_id": 49,
        "question": "Que consirérez-vous comme étant votre principale occupation en ce moment ?",
        "responses": [
            "Recherche d'emploi / sans emploi",
            "Termine mes études secondaires",
            "Études universitaires",
            "Formation professionnelle ",
            "Retours aux études secondaires",
            "Recherche d'emploi",
            "Recherche d'emploi / Sans emploi",
            "Autre",
            "Marché du travail",
            "Armée",
            "Programme jeunesse",
            "Non répondu",
            "Termine mes études postsecondaires",
            "non répondu",
        ],
    },
    {
        "type_id": 2,
        "question_id": 50,
        "question": "Quel est votre état civil présentement ?",
        "responses": [
            "Divorcé/e",
            "Veuf / veuve",
            "Célibataire",
            "Marié/e",
            "Conjoint/e de fait",
            "Séparé/e",
            "Non répondu",
        ],
    },
    {
        "type_id": 2,
        "question_id": 51,
        "question": "De quelle localité de la Péninsule acadienne êtes-vous originaire ?",
        "responses": [
            "AIRDRIE",
            "ROBICHAUD SETTLEMENT",
            "POINTE-A-BOULEAU",
            "ANSE-BLEUE",
            "Granby",
            "BELLEDUNE",
            "BATHURST",
            "NON RÉPONDU",
            "Quispamsis",
            "MONCTON",
            "BELLEDUNE",
            "SAINT-SAUVEUR",
        ],  # shortened for brevity
    },
    {
        "type_id": 2,
        "question_id": 52,
        "question": "Où demeurez-vous présentement ?",
        "responses": [
            "Péninsule acadienne",
            "Ailleurs au N.-B.",
            "Ailleurs au Canada",
            "Dans un autre pays",
            "Non répondu",
        ],
    },
    {
        "type_id": 3,
        "question_id": 1,
        "question": "Dans quelle province canadienne ou ailleurs avez-vous étudié ?",
        "responses": [
            "Angleterre",
            "Québec",
            "Manitoba",
            "Non répondu",
            "Alberta",
            "Saskatchewan",
            "Colombie-Britannique",
            "Ontario",
            "France",
            "Île-du-Prince-Édouard",
            "Nouveau-Brunswick",
            "Nouvelle-Écosse",
            "Terre-Neuve",
        ],
    },
    {
        "type_id": 3,
        "question_id": 2,
        "question": "Durant vos études quelles étaient vos sources de financement ?",
        "responses": [
            "Bourse étudiants",
            "Prêts étudiant",
            "Économie personnelle",
            "Travail à temps partiel",
            "Plan enregistré d'épargne-études",
            "Autre",
            "Travail à temps plein",
            "Prêts/bourse étudiant",
            "Bourse étudiante",
            "Programme d'aide fédéral",
            "Travaille à temps plein",
            "Plan enregistré d'épargnes-études",
            "Programme d'aide provincial",
            "Travaille à temps partiel",
            "Non répondu",
            "Contribution des parents",
        ],
    },
    {
        "type_id": 3,
        "question_id": 3,
        "question": "Seriez-vous intéressé/e à faire un retour aux études ?",
        "responses": [
            "Non",
            "Ne sais pas",
            "Présentement aux études",
            "Non répondu",
            "Oui",
        ],
    },
    {
        "type_id": 3,
        "question_id": 4,
        "question": "Existe-t-il des obstacles qui vous empêchent de poursuivre des études ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
    {
        "type_id": 3,
        "question_id": 5,
        "question": "Seriez-vous intéressé/e à recevoir de l'information pour vous aider dans la poursuite de vos études ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
    {
        "type_id": 3,
        "question_id": 6,
        "question": "Dans quel type d'institution avez-vous étudié ?",
        "responses": ["Universitaire", "Non répondu", "Collégial", "École privée"],
    },
    {
        "type_id": 3,
        "question_id": 7,
        "question": "Quel était votre régime d'études ?",
        "responses": ["Temps plein", "Non répondu", "Temps partiel"],
    },
    {
        "type_id": 3,
        "question_id": 8,
        "question": "Quel était le niveau de votre programme d'études ?",
        "responses": [
            "Troisième cycle ( doctorat )",
            "Deuxième cycle ( maîtrise )",
            "Premier cycle universitaire( bacc., certificat)",
            "Diplôme",
            "Certificat",
            "Non repondu",
            "Cours préparatoire ( 13e année )",
            "Sciences de la santé",
            "Non répondu",
        ],
    },
    {
        "type_id": 3,
        "question_id": 9,
        "question": "Dans quel domaine d'études étiez-vous inscrit/e ?",
        "responses": [
            "Mathématiques, informatique et sciences physiques",
            "Professions de la santé et technologies connexes",
            "Commerce, gestion et administration des affaires",
            "Beaux-arts et arts appliqués",
            "Lettres, sciences humaines et disciplines connexes",
            "Enseignement, loisirs et orientation",
            "Sciences sociales et disciplines connexes",
            "Non repondu",
            "Génie et sciences appliquées",
            "Sans spécialisation",
            "Non répondu",
            "Techniques et métiers des sciences appliquées",
        ],
    },
    {
        "type_id": 3,
        "question_id": 10,
        "question": "Avez-vous complété vos études ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
    {
        "type_id": 4,
        "question_id": 11,
        "question": "Dans quelle province canadienne ou autre pays travaillez-vous ?",
        "responses": [
            "Angleterre",
            "Québec",
            "Manitoba",
            "Non répondu",
            "Territoires-du-Nord-Ouest",
            "Alberta",
            "Saskatchewan",
            "Colombie-Britannique",
            "Nunavut",
            "Ontario",
            "France",
            "Île-du-Prince-Édouard",
            "Nouveau-Brunswick",
            "Suisse",
            "Nouvelle-Écosse",
            "Terre-Neuve",
        ],
    },
    {
        "type_id": 4,
        "question_id": 12,
        "question": "Envisagez-vous de changer d'emploi dans la prochaine année ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
    {
        "type_id": 4,
        "question_id": 13,
        "question": "Quelle est la principale raison pour laquelle vous envisagez de changer d'emploi ?",
        "responses": [
            "Je veux travailler plus près de chez moi",
            "J'ai besoin d'un changement",
            "Mon travail actuel ne correspond pas à mon expérience et à ma formation",
            "Je travaille à temps plein et je préférerais travailler à temps partiel",
            "Je recherche la sécurité d'emploi",
            "Je désire retourner aux études",
        ],
    },
    {
        "type_id": 4,
        "question_id": 14,
        "question": "Dans quelle région de la province travaillez-vous ?",
        "responses": [
            "Nord-Est",
            "Ouest",
            "Nord",
            "Nord-Ouest",
            "Sud",
            "Autre",
            "Centre",
            "Est",
            "Non Répondu",
            "Sud-Est",
            "Non répondu",
            "Sud-Ouest",
            "non répondu",
        ],
    },
    {
        "type_id": 4,
        "question_id": 15,
        "question": "Dans quelle catégorie de profession ou métier travaillez-vous ?",
        "responses": [
            "Commerce de détail",
            "Arts, spectacles et loisirs",
            "Fabrication",
            "Services professionnels, scientifiques et technique",
            "Agriculture, forestierie, pêche et chasse",
            "Services administratifs, services de soutien, services de gestion de déchets et d'assainissement",
            "Finance et assurances",
            "Commerce en gros",
            "Industrie de l'information - industrie culturelle",
            "Transport et entreposage",
            "Non répondu",
            "Services publiques",
            "Hébergement et services de restauration",
            "Gestion de sociétés et d'entreprises",
            "Autre services (sauf administration publique)",
            "Services d'enseignement",
            "Soins de santé et assistance sociale",
            "Extraction minière, extraction de pétrole et de gaz",
            "Services immobiliers, service de location",
            "Construction",
            "Administration publiques",
        ],
    },
    {
        "type_id": 5,
        "question_id": 33,
        "question": "Présentement êtes-vous en attente ou à la recherche d'emploi ?",
        "responses": [
            "Recherche d'emploi",
            "Non",
            "Attente d'emploi",
            "Non répondu",
            "Oui",
        ],
    },
    {
        "type_id": 5,
        "question_id": 34,
        "question": "Au cours des 2 dernières années, combien d'employeurs avez-vous eus ?",
        "responses": ["Un", "Aucun", "Plus de deux", "Non répondu", "Deux"],
    },
    {
        "type_id": 5,
        "question_id": 35,
        "question": "Au cours des deux dernières années, combien de mois d'expérience de travail avez-vous accumulés ?",
        "responses": [
            "Moins de 6 mois",
            "12 à 18 mois",
            "18 à 24 mois",
            "6 à 12 mois",
            "Non répondu",
        ],
    },
    {
        "type_id": 5,
        "question_id": 36,
        "question": "Depuis combien de temps êtes-vous sans emploi ?",
        "responses": [
            "Moins de 6 mois",
            "Plus de 2 ans",
            "1 à 2 ans",
            "6 à 12 mois",
            "Non répondu",
        ],
    },
    {
        "type_id": 5,
        "question_id": 37,
        "question": "Quelle est la principale raison pour laquelle vous n'avez pas travaillé durant cette période ?",
        "responses": [
            "Attente d'un rappel au travail après mise à pied",
            "Invalidité",
            "Accidenté",
            "Rémunération insuffisante pour quitter l'A-S ou A-E",
            "Changement de propriétaire",
            "Chômage / travail saisonnier",
            "Déménagement",
            "Pas de voiture",
            "Conflit de travail",
            "Incapacité de trouver un emploi lié à ma formation",
            "Accouchement",
            "Attente du début d'un emploi",
            "Chômage de quelques semaines",
            "Retour aux études",
            "Responsabilité personnelles ou familiales",
            "Non répondu",
            "Maladie",
        ],
    },
    {
        "type_id": 5,
        "question_id": 38,
        "question": "Seriez-vous intéressé/e par une expérience de travail dans votre communauté ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
    {
        "type_id": 5,
        "question_id": 39,
        "question": "Seriez-vous intéressé à recevoir des l'information concernant une expérience de travail dans votre communauté ?",
        "responses": ["Non", "Non répondu", "Oui"],
    },
    {
        "type_id": 5,
        "question_id": 40,
        "question": "Êtes-vous disponible pour travailler maintenant ?",
        "responses": ["Non", "Non répondu", "Oui"],
    },
    {
        "type_id": 5,
        "question_id": 41,
        "question": "Quel type d'emploi recherchez-vous ?",
        "responses": [
            "Commerce de détail",
            "Arts, spectacles et loisirs",
            "Fabrication",
            "Services professionnels, scientifiques et technique",
            "Agriculture, forestierie, pêche et chasse",
            "Services admistratifs, services de soutien, services de gestion de déchets et d'assainissement",
            "Finance et assurances ",
            "Commerce en gros",
            "Insdustrie de l'information - industrie culturelle",
            "Transport et entreposage",
            "Non répondu",
            "Services publiques",
            "Hébergement et services de restauration",
            "Gestion de sociétés et d'entreprises",
            "Autre services (sauf administration publique)",
            "Services d'enseignement",
            "Soins de santé et assistance sociale",
            "Extraction minière, extraction de pétrole et de gaz ",
            "Construction",
            "Administration publiques",
        ],
    },
    {
        "type_id": 5,
        "question_id": 42,
        "question": "Dans quelle province canadienne ou autre pays aimeriez-vous travailler ?",
        "responses": [
            "Alberta",
            "Saskatchewan",
            "Autre",
            "Colombie-Britanique",
            "Ontario",
            "Terre-Neuve",
            "Nouveau-Brunswick",
            "Québec",
            "Non répondu",
            "non répondu",
        ],
    },
    {
        "type_id": 5,
        "question_id": 43,
        "question": "Dans quelle région de la province aimeriez-vous travailler ?",
        "responses": [
            "Nord-Est",
            "Saskatchewan",
            "Nord",
            "Sud-ESt",
            "Nord-Ouest",
            "Sud",
            "Colombie-Britanique",
            "Autre",
            "Terre-Neuve",
            "Nouveau-Brunswick",
            "Sud-Est",
            "Non répondu",
            "Sud-Ouest",
        ],
    },
    {
        "type_id": 5,
        "question_id": 44,
        "question": "Avez-vous eu un emploi au cours des 2 dernières années ?",
        "responses": ["Non répondu", "Non", "Oui"],
    },
]

documents = []
for item in data:
    page_content = item["question"] + "\n" + str(item["responses"])
    metadata = {"type_id": item["type_id"], "question_id": item["question_id"]}
    document = Document(page_content=page_content, metadata=metadata)
    documents.append(document)

# Now 'documents' is a list of Document objects in the desired format.

# Example of accessing the data:
# print(documents[0].page_content)
# print(documents[0].metadata)
# print(documents)

from langchain_voyageai import VoyageAIEmbeddings, VoyageAIRerank

if not os.environ.get("VOYAGE_API_KEY"):
    os.environ["VOYAGE_API_KEY"] = "pa-_GyP9a57BCZa2sX0mRJtQRfK49fTEmTRB2vg23Bgygs"
embeddings = VoyageAIEmbeddings(model="voyage-3-large")


import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)
uuids = [str(uuid4()) for _ in range(len(documents))]

vector_store.add_documents(documents=documents, ids=uuids)

vector_store.save_local("faiss_index_db_questions")

new_vector_store = FAISS.load_local(
    "faiss_index_db_questions", embeddings, allow_dangerous_deserialization=True
)


from langchain.retrievers.contextual_compression import ContextualCompressionRetriever

compression_retriever = ContextualCompressionRetriever(
    base_compressor=VoyageAIRerank(model="rerank-2", top_k=2),
    base_retriever=new_vector_store.as_retriever(search_kwargs={"k": 6}),
)
# kwargs (Any) – Additional arguments to pass to the retriever. #TODO add two filter boxes aswell
results = compression_retriever.invoke(
    "bourses",
    filter={"type_id": 3},
)
print(results)
for doc in results:
    print(
        f"\n\n [SIM={doc.metadata["relevance_score"]:3f}] {doc.page_content} [{doc.metadata}] "
    )


# def display_results_in_sidebar(results):
#     """
#     Displays the top retrieved documents in the Streamlit sidebar.

#     Args:
#         results: A list of langchain.docstore.document.Document objects.
#     """
#     st.sidebar.header("Search Results")  # Add a header to the sidebar

#     if not results:
#         st.sidebar.write("No results found.")
#         return

#     for i, doc in enumerate(results):
#         st.sidebar.subheader(f"Result {i+1}")  # Add a subheader for each result
#         st.sidebar.write(f"**Question ID:** {doc.metadata['question_id']}")
#         st.sidebar.write(f"**Type ID:** {doc.metadata['type_id']}")
#         st.sidebar.write(f"**Content:** {doc.page_content}")
#         st.sidebar.markdown("---")  # Add a separator between results

# # Example usage (assuming you have a list of Document objects called 'results'):
# # display_results_in_sidebar(results)
