questions = [
    "Pour l'école 'Centre La Fontaine' en 2006, combien d'étudiants ont répondu 'Très satisfait/e' à la question 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'",
    "Comment a évolué le pourcentage de réponses 'Cégep' à la question 'Que prévoyez-vous faire en septembre prochain ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, quel est le nombre de réponses 'Lettres, sciences humaines et disciplines connexes' à la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Pas du tout' à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour l'école 'W.-A.-Losier' en 2009, combien d'étudiants ont choisi 'Je ne sais pas' comme réponse à la question 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?'",
    "Comment a évolué le taux de réponses '1. Dans la Péninsule acadienne' à la question 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour chaque école en 2016, combien d'étudiants ont répondu 'Université de Moncton - campus Edmunston' à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'",
    "Quelle est l'évolution du nombre de réponses '3. Contribution des parents' à la question 'Durant vos études postsecondaires, quelles seront vos sources de financement ?' pour l'école 'Secondaire Népisiguit' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2014, combien d'étudiants ont choisi '1. À pied' comme réponse à la question 'Quel moyen de transport local pensez-vous utiliser le plus régulièrement pendant votre première année d'études ?'",
    "Comment a évolué le pourcentage de réponses 'Accès au marché du travail' à la question 'Quelle est la raison pour laquelle vous ne prévoyez pas poursuivre des études postsecondaire ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2018, quel est le nombre de réponses '2. Temps partiel fin de semaine' à la question 'Depuis septembre dernier, avez-vous occupé un emploi rénuméré ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Très important' à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2004, combien d'étudiants ont choisi 'de 81 % à 94 %' comme réponse à la question 'En général, quels sont vos résultats scolaires en 10e 11e et 12e année ?'",
    "Comment a évolué le taux de réponses 'Régulier' à la question 'En général, vos cours sont de quel niveau scolaire ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, combien d'étudiants ont répondu 'Satisfait/e' à la question 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'",
    "Quelle est l'évolution du nombre de réponses 'Deux ans' à la question 'Depuis combien d'années demeurez-vous à l'extérieur de la Péninsule acadienne ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Travail' comme réponse à la question 'Pour quelle raison avez-vous quitté la Péninsule acadienne ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Avez-vous l'intention de vous établir dans la Péninsule acadienne au cours des cinq prochaines années ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, quel est le nombre de réponses 'Secondaire (12 ième année)' à la question 'Quel est votre niveau d'éducation le plus élevé ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Marché du travail' à la question 'Que consirérez-vous comme étant votre principale occupation en ce moment ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2011, combien d'étudiants ont choisi 'Marié/e' comme réponse à la question 'Quel est votre état civil présentement ?'",
    "Comment a évolué le taux de réponses 'AIRDRIE' à la question 'De quelle localité de la Péninsule acadienne êtes-vous originaire ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, combien d'étudiants ont répondu 'Péninsule acadienne' à la question 'Où demeurez-vous présentement ?'",
    "Quelle est l'évolution du nombre de réponses 'Nouveau-Brunswick' à la question 'Dans quelle province canadienne ou ailleurs avez-vous étudié ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2018, combien d'étudiants ont choisi 'Prêts étudiant' comme réponse à la question 'Durant vos études quelles étaient vos sources de financement ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Seriez-vous intéressé/e à faire un retour aux études ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, quel est le nombre de réponses 'Oui' à la question 'Existe-t-il des obstacles qui vous empêchent de poursuivre des études ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Oui' à la question 'Seriez-vous intéressé/e à recevoir de l'information pour vous aider dans la poursuite de vos études ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2005, combien d'étudiants ont choisi 'Universitaire' comme réponse à la question 'Dans quel type d'institution avez-vous étudié ?'",
    "Comment a évolué le taux de réponses 'Temps partiel' à la question 'Quel était votre régime d'études ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, combien d'étudiants ont répondu 'Premier cycle universitaire( bacc., certificat)' à la question 'Quel était le niveau de votre programme d'études ?'",
    "Quelle est l'évolution du nombre de réponses 'Professions de la santé et technologies connexes' à la question 'Dans quel domaine d'études étiez-vous inscrit/e ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Non' comme réponse à la question 'Avez-vous complété vos études ?'",
    "Comment a évolué le pourcentage de réponses 'Nouveau-Brunswick' à la question 'Dans quelle province canadienne ou autre pays travaillez-vous ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2018, quel est le nombre de réponses 'Non' à la question 'Envisagez-vous de changer d'emploi dans la prochaine année ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Je veux travailler plus près de chez moi' à la question 'Quelle est la principale raison pour laquelle vous envisagez de changer d'emploi ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2010, combien d'étudiants ont choisi 'Nord' comme réponse à la question 'Dans quelle région de la province travaillez-vous ?'",
    "Comment a évolué le taux de réponses 'Commerce de détail' à la question 'Dans quelle catégorie de profession ou métier travaillez-vous ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, combien d'étudiants ont répondu 'Oui' à la question 'Présentement êtes-vous en attente ou à la recherche d'emploi ?'",
    "Quelle est l'évolution du nombre de réponses 'Aucun' à la question 'Au cours des 2 dernières années, combien d'employeurs avez-vous eus ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2018, combien d'étudiants ont choisi 'Moins de 6 mois' comme réponse à la question 'Au cours des deux dernières années, combien de mois d'expérience de travail avez-vous accumulés ?'",
    "Comment a évolué le pourcentage de réponses 'Moins de 6 mois' à la question 'Depuis combien de temps êtes-vous sans emploi ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, quel est le nombre de réponses 'Chômage / travail saisonnier' à la question 'Quelle est la principale raison pour laquelle vous n'avez pas travaillé durant cette période ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Oui' à la question 'Seriez-vous intéressé/e par une expérience de travail dans votre communauté ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2007, combien d'étudiants ont choisi 'Oui' comme réponse à la question 'Seriez-vous intéressé à recevoir des l'information concernant une expérience de travail dans votre communauté ?'",
    "Comment a évolué le taux de réponses 'Oui' à la question 'Êtes-vous disponible pour travailler maintenant ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, combien d'étudiants ont répondu 'Commerce de détail' à la question 'Quel type d'emploi recherchez-vous ?'",
    "Quelle est l'évolution du nombre de réponses 'Québec' à la question 'Dans quelle province canadienne ou autre pays aimeriez-vous travailler ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Nord' comme réponse à la question 'Dans quelle région de la province aimeriez-vous travailler ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Avez-vous eu un emploi au cours des 2 dernières années ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?"
    "Pour l’année 2018, pour l'école 'Aux quatre vents', fournir le nombre de réponses pour l’option 'Prêt étudiant' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2018, pour l'école 'Aux quatre vents', agréger le nombre de réponses pour l’option 'Bourses étudiantes' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2018, pour l'école 'Aux quatre vents', compter le nombre de réponses pour l’option 'Contribution des parents' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2018, pour l'école 'Aux quatre vents', fournir la répartition des réponses pour l’option 'Travail à temps partiel' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2017, pour l'école 'Centre La Fontaine', agréger le nombre de réponses 'Très satisfait/e' à la question complète 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2017, pour l'école 'Centre La Fontaine', compter le nombre de réponses 'Très insatisfait/e' à la question complète 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2016, pour l'école 'Centre La Fontaine', fournir la distribution des réponses pour l’option 'Cégep' dans la question complète 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2016, pour l'école 'Centre La Fontaine', compter le nombre de réponses 'Non répondu' dans la question complète 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2015, pour l'école 'Secondaire Népisiguit', calculer le pourcentage des réponses positives à la question complète 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' en se concentrant sur l’option 'Très bien'.",
    "Pour l’année 2015, pour l'école 'Secondaire Népisiguit', agréger le nombre de réponses 'Bien' à la question complète 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?'.",
    "Pour la période 2004-2012, pour l'école 'Louis-Mailloux', fournir l’évolution annuelle du taux de réponse à la question complète 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'.",
    "Pour l’année 2019, pour l'école 'Louis-Mailloux', agréger le nombre de réponses pour l’option 'Commerce, gestion et administration des affaires' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2019, pour l'école 'Louis-Mailloux', compter le nombre de réponses pour l’option 'Lettres, sciences humaines et disciplines connexes' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2019, pour l'école 'Louis-Mailloux', fournir la distribution des réponses pour l’option 'Génie et sciences appliquées' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2014, pour l'école 'Marie-Esther', donner le nombre de réponses 'Oui' à la question complète 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?'.",
    "Pour l’année 2014, pour l'école 'Marie-Esther', agréger le nombre de réponses 'Non' à la question complète 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?'.",
    "Pour l’année 2018, pour l'école 'Marie-Esther', fournir la répartition des réponses pour l’option 'Dans la Péninsule acadienne' dans la question complète 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?'.",
    "Pour l’année 2018, pour l'école 'Marie-Esther', compter le nombre de réponses pour l’option 'Canada' dans la question complète 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?'.",
    "Pour l’année 2018, pour l'école 'Marie-Esther', fournir la distribution des réponses pour l’option 'Ontario' dans la question complète 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?'.",
    "Pour l’année 2017, pour l'école 'Roland-Pépin', fournir le nombre de réponses pour l’option 'Université Laval' dans la question complète 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'.",
    "Pour l’année 2017, pour l'école 'Roland-Pépin', compter le nombre de réponses pour l’option 'Université de Montréal' dans la question complète 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'.",
    "Pour l’année 2013, pour l'école 'Roland-Pépin', agréger la répartition des réponses pour l’option 'Autre' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2013, pour l'école 'Roland-Pépin', fournir le nombre de réponses pour l’option 'Économie personnelle' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2013, pour l'école 'Roland-Pépin', compter le nombre de réponses pour l’option 'Contribution des parents' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2013, pour l'école 'Roland-Pépin', agréger le nombre de réponses pour l’option 'Travail à temps partiel' dans la question complète 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'.",
    "Pour l’année 2012, pour l'école 'W.-A.-Losier', fournir la répartition des réponses pour l’option 'Très satisfait/e' dans la question complète 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'.",
    "Pour l’année 2012, pour l'école 'W.-A.-Losier', compter le nombre de réponses 'Insatisfait/e' à la question complète 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'.",
    "Pour l’année 2012, pour l'école 'W.-A.-Losier', fournir le nombre de réponses 'Non répondu' à la question complète 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'.",
    "Pour l’année 2011, pour l'école 'Aux quatre vents', calculer le taux de réponses pour l’option 'Régulier' dans la question complète 'En général, vos cours sont de quel niveau scolaire ?'.",
    "Pour l’année 2011, pour l'école 'Aux quatre vents', agréger le nombre de réponses pour l’option 'Adaptation scolaire' dans la question complète 'En général, vos cours sont de quel niveau scolaire ?'.",
    "Pour l’année 2011, pour l'école 'Aux quatre vents', fournir la distribution des réponses pour l’option 'Compétences essentielles' dans la question complète 'En général, vos cours sont de quel niveau scolaire ?'.",
    "Pour l’année 2010, pour l'école 'Centre La Fontaine', analyser la répartition des réponses pour l’option 'Formation professionnelle' dans la question complète 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2010, pour l'école 'Centre La Fontaine', compter le nombre de réponses 'Non répondu' dans la question complète 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2010, pour l'école 'Centre La Fontaine', fournir le nombre de réponses pour l’option 'Programmes jeunesse' dans la question complète 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2009, pour l'école 'Secondaire Népisiguit', agréger le nombre de réponses pour l’option 'Sciences sociales' dans la question complète 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2009, pour l'école 'Secondaire Népisiguit', compter le nombre de réponses pour l’option 'Sc. De l'environnement' dans la question complète 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2009, pour l'école 'Secondaire Népisiguit', agréger le nombre de réponses pour l’option 'Technologie' dans la question complète 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2009, pour l'école 'Secondaire Népisiguit', fournir le nombre de réponses pour l’option 'Droit' dans la question complète 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2008, pour l'école 'Louis-Mailloux', analyser la répartition des réponses pour l’option 'Très satisfait/e' dans la question complète 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2008, pour l'école 'Louis-Mailloux', agréger le nombre de réponses pour l’option 'Insatisfait/e' dans la question complète 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2008, pour l'école 'Louis-Mailloux', compter le nombre de réponses 'Non répondu' à la question complète 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2007, pour l'école 'Marie-Esther', fournir la répartition des réponses pour l’option 'Sciences sociales et disciplines connexes' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2007, pour l'école 'Marie-Esther', agréger le nombre de réponses pour l’option 'Génie et sciences appliquées' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2007, pour l'école 'Marie-Esther', analyser le nombre de réponses indiquant 'Sans spécialisation' dans la question complète 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2006, pour l'école 'Roland-Pépin', compter le nombre de réponses pour l’option 'Très important' à la question complète 'Est-ce que le fait de terminer votre 12e année est important pour vous ?'.",
    "Pour l’année 2006, pour l'école 'Roland-Pépin', agréger le nombre de réponses pour l’option 'Pas du tout important' à la question complète 'Est-ce que le fait de terminer votre 12e année est important pour vous ?'.",
    "Pour l’année 2006, pour l'école 'Roland-Pépin', fournir le nombre de réponses 'Non répondu' à la question complète 'Est-ce que le fait de terminer votre 12e année est important pour vous ?'.",
    "Pour l’année 2010, pour l'école 'W.-A.-Losier', compter le nombre de réponses 'Oui' à la question complète 'Seriez-vous intéressé/e à faire un retour aux études ?'.",
    "Pour l’année 2010, pour l'école 'W.-A.-Losier', agréger le nombre de réponses 'Non' à la question complète 'Seriez-vous intéressé/e à faire un retour aux études ?'.",
    "Pour l’année 2019, pour l'école 'W.-A.-Losier', analyser la répartition des réponses pour l’option 'Universitaire' dans la question complète 'Dans quel type d'institution avez-vous étudié ?'."
    "Pour l'école Aux quatre vents en 2018, quelle était la répartition des réponses à la question 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?' ?",
    "Comment a évolué le pourcentage d'élèves de l'école Marie-Esther qui ont indiqué 'Professions de la santé et technologies connexes' comme domaine d'études postsecondaires entre 2004 et 2012 ?",
    "Pour l'école W.-A.-Losier en 2019, quel est le pourcentage d'étudiants qui considèrent que terminer leur 12e année est 'Très important' ?",
    "Comment se compare la satisfaction des étudiants concernant leurs résultats scolaires entre les écoles Louis-Mailloux et Marie-Esther pour l'année 2008 ?",
    "Pour l'école Centre La Fontaine en 2011, quelle était la répartition des réponses à la question 'Au cours des 2 dernières années, combien d'employeurs avez-vous eus ?' ?",
    "Quelle école parmi Aux quatre vents, Roland-Pépin et Secondaire Népisiguit en 2016 présentait la plus forte proportion d'élèves indiquant être 'Satisfait/e' de leurs relations avec le personnel de l'école ?",
    "Pour l'école Louis-Mailloux en 2007, quel pourcentage d'étudiants a indiqué 'Biologie' comme l'un des deux cours les plus appréciés durant leur secondaire ?",
    "Comment a évolué la proportion d'étudiants de l'école W.-A.-Losier qui ont indiqué être intéressés à faire un retour aux études entre 2004 et 2012 ?",
    "Pour l'école Secondaire Népisiguit en 2018, quelle était la répartition des niveaux scolaires des cours suivis par les étudiants ?",
    "Quelles différences peut-on observer entre les écoles Marie-Esther et Centre La Fontaine en 2012 concernant le pourcentage d'étudiants qui considéraient leurs cours comme étant de niveau 'Régulier' ?",
    "Pour l'école Aux quatre vents en 2015, quelle était la proportion d'étudiants qui prévoyaient utiliser le 'Transport en commun' comme moyen de transport durant leur première année d'études ?",
    "Comment a évolué le taux d'étudiants indiquant 'Marché du travail' comme prévision pour septembre prochain à l'école Secondaire Népisiguit entre 2014 et 2019 ?",
    "Pour l'école Roland-Pépin en 2019, quelle est la répartition des réponses à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' ?",
    "Quelle école entre W.-A.-Losier et Louis-Mailloux présentait en 2006 le plus grand écart entre les réponses 'Oui' et 'Non' à la question 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?' ?",
    "Pour l'école Marie-Esther en 2005, quel était le pourcentage d'étudiants qui ont indiqué être intéressés à recevoir de l'information pour les aider dans la poursuite de leurs études ?",
    "Comment a évolué la proportion d'étudiants de l'école Centre La Fontaine indiquant 'Université de Moncton - campus Shippagan' comme institution qu'ils pensaient fréquenter l'année suivante entre 2004 et 2012 ?",
    "Pour l'école W.-A.-Losier en 2004, quelle était la répartition des réponses à la question 'Où demeurez-vous présentement ?' ?",
    "Quelle école parmi Marie-Esther, Louis-Mailloux et W.-A.-Losier présentait en 2010 le plus fort pourcentage d'étudiants dont le régime d'études était 'Temps plein' ?",
    "Pour l'école Aux quatre vents en 2017, quelle était la proportion d'élèves qui ont indiqué que les services d'orientation avaient 'Bien' répondu à leurs besoins ?",
    "Comment a évolué le pourcentage d'étudiants de l'école Secondaire Népisiguit qui avaient des résultats scolaires 'de 81 % à 94 %' entre 2014 et 2019 ?",
    "Pour l'école Louis-Mailloux en 2009, quelle était la répartition des réponses à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?' ?",
    "Quelle différence observe-t-on entre les écoles Roland-Pépin et Secondaire Népisiguit en 2015 concernant la proportion d'étudiants qui ont indiqué 'Mathématiques' comme l'un des cours les plus appréciés ?",
    "Pour l'école Centre La Fontaine en 2006, quel était le pourcentage d'étudiants qui ont indiqué être en attente d'emploi ?",
    "Comment a évolué la proportion d'étudiants de l'école Marie-Esther qui prévoyaient travailler au 'Nouveau-Brunswick' après leurs études postsecondaires entre 2004 et 2012 ?",
    "Pour l'école W.-A.-Losier en 2008, quelle était la répartition des réponses à la question 'Depuis combien d'années demeurez-vous à l'extérieur de la Péninsule acadienne ?' ?",
    "Quelles différences peut-on observer entre les écoles Louis-Mailloux et Centre La Fontaine en 2007 concernant le type d'emploi recherché par les étudiants ?",
    "Pour l'école Secondaire Népisiguit en 2019, quel était le pourcentage d'élèves qui ont indiqué être 'Très satisfait/e' de leurs relations avec le personnel de l'école ?",
    "Comment a évolué la proportion d'étudiants de l'école Aux quatre vents qui prévoyaient aller sur le 'Marché du travail' en septembre prochain entre 2014 et 2019 ?",
    "Pour l'école Roland-Pépin en 2018, quelle était la répartition des résultats scolaires des étudiants ?",
    "Quelle école parmi Marie-Esther, W.-A.-Losier et Louis-Mailloux présentait en 2011 le plus fort pourcentage d'étudiants ayant indiqué 'Travail à temps partiel' comme source de financement pour leurs études postsecondaires ?",
    "Pour l'école Centre La Fontaine en 2008, quel était le pourcentage d'étudiants qui ont indiqué 'Universitaire' comme type d'institution où ils avaient étudié ?",
    "Comment a évolué le pourcentage d'élèves de l'école Louis-Mailloux qui ont indiqué être disponibles pour travailler maintenant entre 2004 et 2012 ?",
    "Pour l'école W.-A.-Losier en 2012, quelle était la répartition des réponses à la question 'Présentement êtes-vous en attente ou à la recherche d'emploi ?' ?",
    "Quelle différence observe-t-on entre les écoles Aux quatre vents et Roland-Pépin en 2017 concernant la proportion d'étudiants qui ont indiqué que terminer leur 12e année était 'Important' pour eux ?",
    "Pour l'école Marie-Esther en 2004, quel était le pourcentage d'étudiants qui indiquaient avoir complété leurs études postsecondaires ?",
    "Comment a évolué la proportion d'étudiants de l'école Secondaire Népisiguit qui ont indiqué 'Prêt étudiant' comme source de financement pour leurs études postsecondaires entre 2014 et 2019 ?",
    "Pour l'école Louis-Mailloux en 2006, quelle était la répartition des domaines dans lesquels les étudiants avaient l'intention de poursuivre leurs études postsecondaires ?",
    "Quelle école parmi Centre La Fontaine, Marie-Esther et W.-A.-Losier présentait en 2005 le plus fort pourcentage d'élèves étant 'Très satisfait/e' de leur séjour au secondaire sur le plan des relations avec les autres élèves ?",
    "Pour l'école Roland-Pépin en 2014, quelle était la proportion d'étudiants qui prévoyaient utiliser 'À pied' comme moyen de transport pendant leur première année d'études ?",
    "Comment a évolué le pourcentage d'étudiants de l'école Aux quatre vents indiquant être 'Satisfait/e' de leurs résultats scolaires entre 2014 et 2019 ?",
    "Pour l'école Centre La Fontaine en 2010, quelle était la répartition des réponses à la question 'Seriez-vous intéressé/e par une expérience de travail dans votre communauté ?' ?",
    "Quelle différence observe-t-on entre les écoles W.-A.-Losier et Marie-Esther en 2009 concernant la proportion d'élèves qui considéraient que terminer leur 12e année était 'Très important' ?",
    "Pour l'école Secondaire Népisiguit en 2016, quel était le pourcentage d'étudiants qui ont indiqué 'Études universitaires' comme prévision pour septembre prochain ?",
    "Comment a évolué la proportion d'étudiants de l'école Louis-Mailloux qui indiquaient 'Nouveau-Brunswick' comme province où ils aimeraient travailler entre 2004 et 2012 ?",
    "Pour l'école Marie-Esther en 2011, quelle était la répartition des niveaux de programme d'études suivis par les étudiants ?",
    "Quelle école entre Roland-Pépin et Aux quatre vents présentait en 2015 le plus fort pourcentage d'étudiants dont les cours étaient de niveau 'Régulier' ?",
    "Pour l'école W.-A.-Losier en 2007, quel était le pourcentage d'étudiants qui ont indiqué 'Retour aux études' comme raison principale pour laquelle ils n'avaient pas travaillé durant une certaine période ?",
    "Comment a évolué la répartition des réponses à la question 'Quel est votre état civil présentement ?' pour les étudiants de l'école Centre La Fontaine entre 2004 et 2012 ?",
    "Pour l'école Aux quatre vents en 2019, quelle était la proportion d'élèves qui ont indiqué que les services d'orientation n'avaient 'Pas du tout' répondu à leurs besoins ?",
    "Quelle différence observe-t-on entre les écoles Secondaire Népisiguit et Roland-Pépin en 2018 concernant la proportion d'étudiants qui prévoyaient poursuivre des études dans le domaine 'Professions de la santé et technologies connexes' ?"
    "Pour l'école 'Marie-Esther' en 2015, combien d'étudiants ont répondu 'Satisfait/e' à la question 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour chaque école en 2018, quel est le nombre de réponses 'Prêt étudiant' à la question 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Temps partiel fin de semaine' à la question 'Depuis septembre dernier, avez-vous occupé un emploi rénuméré ?' pour l'école 'Centre La Fontaine' entre 2004 et 2012 ?",
    "Pour l'école 'W.-A.-Losier' en 2010, combien d'étudiants ont choisi 'Université de Moncton - campus Moncton' comme réponse à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'",
    "Comment a évolué le taux de réponses 'Non' à la question 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour chaque école en 2016, combien d'étudiants ont répondu 'Études universitaires' à la question 'Que prévoyez-vous faire en septembre prochain ?'",
    "Quelle est l'évolution du nombre de réponses 'Peu' à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' pour l'école 'Secondaire Népisiguit' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Commerce, gestion et administration des affaires' comme réponse à la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Seriez-vous intéressé/e à faire un retour aux études ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, quel est le nombre de réponses 'Travail à temps partiel' à la question 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Non' à la question 'Depuis combien d'années demeurez-vous à l'extérieur de la Péninsule acadienne ?' pour l'école 'Centre La Fontaine' entre 2004 et 2012 ?",
    "Pour l'école 'Louis-Mailloux' en 2008, combien d'étudiants ont choisi 'Étude' comme réponse à la question 'Pour quelle raison avez-vous quitté la Péninsule acadienne ?'",
    "Comment a évolué le taux de réponses 'Oui' à la question 'Avez-vous l'intention de vous établir dans la Péninsule acadienne au cours des cinq prochaines années ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, combien d'étudiants ont répondu 'Secondaire (12 ième année)' à la question 'Quel est votre niveau d'éducation le plus élevé ?'",
    "Quelle est l'évolution du nombre de réponses 'Recherche d'emploi / sans emploi' à la question 'Que consirérez-vous comme étant votre principale occupation en ce moment ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2018, combien d'étudiants ont choisi 'Célibataire' comme réponse à la question 'Quel est votre état civil présentement ?'",
    "Comment a évolué le pourcentage de réponses 'Québec' à la question 'Dans quelle province canadienne ou ailleurs avez-vous étudié ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, quel est le nombre de réponses 'Bourse étudiants' à la question 'Durant vos études quelles étaient vos sources de financement ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Non' à la question 'Seriez-vous intéressé/e à faire un retour aux études ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2005, combien d'étudiants ont choisi 'Non' comme réponse à la question 'Existe-t-il des obstacles qui vous empêchent de poursuivre des études ?'",
    "Comment a évolué le taux de réponses 'Oui' à la question 'Seriez-vous intéressé/e à recevoir de l'information pour vous aider dans la poursuite de vos études ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, combien d'étudiants ont répondu 'Universitaire' à la question 'Dans quel type d'institution avez-vous étudié ?'",
    "Quelle est l'évolution du nombre de réponses 'Temps plein' à la question 'Quel était votre régime d'études ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Premier cycle universitaire( bacc., certificat)' comme réponse à la question 'Quel était le niveau de votre programme d'études ?'",
    "Comment a évolué le pourcentage de réponses 'Mathématiques, informatique et sciences physiques' à la question 'Dans quel domaine d'études étiez-vous inscrit/e ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2018, quel est le nombre de réponses 'Non' à la question 'Avez-vous complété vos études ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Québec' à la question 'Dans quelle province canadienne ou autre pays travaillez-vous ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2011, combien d'étudiants ont choisi 'Non' comme réponse à la question 'Envisagez-vous de changer d'emploi dans la prochaine année ?'",
    "Comment a évolué le taux de réponses 'Je veux travailler plus près de chez moi' à la question 'Quelle est la principale raison pour laquelle vous envisagez de changer d'emploi ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, combien d'étudiants ont répondu 'Nord' à la question 'Dans quelle région de la province travaillez-vous ?'",
    "Quelle est l'évolution du nombre de réponses 'Commerce de détail' à la question 'Dans quelle catégorie de profession ou métier travaillez-vous ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2017, combien d'étudiants ont choisi 'Non' comme réponse à la question 'Présentement êtes-vous en attente ou à la recherche d'emploi ?'",
    "Comment a évolué le pourcentage de réponses 'Aucun' à la question 'Au cours des 2 dernières années, combien d'employeurs avez-vous eus ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2018, quel est le nombre de réponses 'Moins de 6 mois' à la question 'Au cours des deux dernières années, combien de mois d'expérience de travail avez-vous accumulés ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Moins de 6 mois' à la question 'Depuis combien de temps êtes-vous sans emploi ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2007, combien d'étudiants ont choisi 'Chômage / travail saisonnier' comme réponse à la question 'Quelle est la principale raison pour laquelle vous n'avez pas travaillé durant cette période ?'",
    "Comment a évolué le taux de réponses 'Oui' à la question 'Seriez-vous intéressé/e par une expérience de travail dans votre communauté ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, combien d'étudiants ont répondu 'Oui' à la question 'Seriez-vous intéressé à recevoir des l'information concernant une expérience de travail dans votre communauté ?'",
    "Quelle est l'évolution du nombre de réponses 'Oui' à la question 'Êtes-vous disponible pour travailler maintenant ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2019, combien d'étudiants ont choisi 'Commerce de détail' comme réponse à la question 'Quel type d'emploi recherchez-vous ?'",
    "Comment a évolué le pourcentage de réponses 'Québec' à la question 'Dans quelle province canadienne ou autre pays aimeriez-vous travailler ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2017, quel est le nombre de réponses 'Nord' à la question 'Dans quelle région de la province aimeriez-vous travailler ?'",
    "Quelle est l'évolution du nombre d'étudiants ayant répondu 'Oui' à la question 'Avez-vous eu un emploi au cours des 2 dernières années ?' pour l'école 'Louis-Mailloux' entre 2004 et 2019 ?",
    "Pour l'école 'Centre La Fontaine' en 2010, combien d'étudiants ont choisi 'Non' comme réponse à la question 'Présentement êtes-vous en attente ou à la recherche d'emploi ?'",
    "Comment a évolué le taux de réponses 'Deux' à la question 'Au cours des 2 dernières années, combien d'employeurs avez-vous eus ?' pour l'école 'W.-A.-Losier' entre 2004 et 2019 ?",
    "Pour chaque école en 2016, combien d'étudiants ont répondu '18 à 24 mois' à la question 'Au cours des deux dernières années, combien de mois d'expérience de travail avez-vous accumulés ?'",
    "Quelle est l'évolution du nombre de réponses '1 à 2 ans' à la question 'Depuis combien de temps êtes-vous sans emploi ?' pour l'école 'Roland-Pépin' entre 2014 et 2019 ?",
    "Pour l'école 'Aux quatre vents' en 2018, combien d'étudiants ont choisi 'Chômage / travail saisonnier' comme réponse à la question 'Quelle est la principale raison pour laquelle vous n'avez pas travaillé durant cette période ?'",
    "Comment a évolué le pourcentage de réponses 'Oui' à la question 'Seriez-vous intéressé/e par une expérience de travail dans votre communauté ?' pour l'école 'Marie-Esther' entre 2004 et 2019 ?",
    "Pour chaque école en 2015, quel est le nombre de réponses 'Oui' à la question 'Seriez-vous intéressé à recevoir des l'information concernant une expérience de travail dans votre communauté ?'"
    "Pour l’année 2018, pour chaque école, fournir le nombre de réponses pour la source de financement 'Prêt étudiant' dans la question 'Durant vos études postsecondaires, quelles seront vos sources de financement ?'",
    "Pour l’année 2018, pour chaque école, fournir le nombre de réponses pour l’option 'Bourses étudiantes' dans la question sur les sources de financement durant les études postsecondaires.",
    "Pour l’année 2018, pour chaque école, indiquer le nombre de réponses pour l’option 'Contribution des parents' dans la question sur les sources de financement durant les études postsecondaires.",
    "Pour l’année 2018, pour chaque école, fournir le nombre de réponses pour l’option 'Travail à temps partiel' dans la question sur les sources de financement durant les études postsecondaires.",
    "Pour chaque école en 2017, agréger le nombre de réponses 'Très satisfait/e' à la question 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?'",
    "Pour chaque école en 2017, compter le nombre de réponses 'Insatisfait/e' à la question 'Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ?'",
    "Pour l’année 2016, pour chaque école, fournir la répartition des réponses à la question 'Que prévoyez-vous faire en septembre prochain ?' en se concentrant sur les options 'Cégep', 'Études collégiales' et 'Études universitaires'.",
    "Pour l’année 2016, pour chaque école, compter le nombre de réponses 'Non répondu' dans la question 'Que prévoyez-vous faire en septembre prochain ?'",
    "Pour chaque école en 2015, calculer le pourcentage d’élèves ayant répondu à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?'",
    "Pour chaque école, sur la période 2004-2012, fournir l’évolution annuelle du taux de réponse à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?'",
    "Pour l’année 2019, pour chaque école, agréger le nombre de réponses à la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?' en se focalisant sur l’option 'Commerce, gestion et administration des affaires'.",
    "Pour l’année 2019, pour chaque école, compter le nombre de réponses indiquant 'Lettres, sciences humaines et disciplines connexes' dans la question sur le domaine d’études postsecondaires envisagé.",
    "Pour l’année 2019, pour chaque école, fournir la distribution des réponses pour l’option 'Génie et sciences appliquées' dans la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'",
    "Pour l’année 2014, pour chaque école, donner le nombre de réponses 'Oui' à la question 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?'",
    "Pour l’année 2014, pour chaque école, calculer le nombre de réponses 'Non' à la question sur l’acceptation d’une offre d’emploi dans la Péninsule acadienne.",
    "Pour l’année 2018, pour chaque école, agréger le nombre de réponses à la question 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?' pour l’option 'Dans la Péninsule acadienne'.",
    "Pour l’année 2018, pour chaque école, compter les réponses à la question 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?' pour l’option 'Canada'.",
    "Pour l’année 2018, pour chaque école, fournir la répartition des réponses à la question 'Lorsque vous aurez terminé vos études postsecondaires, indiquez où vous prévoyez travailler ?' en se focalisant sur l’option 'Ontario'.",
    "Pour l’année 2017, pour chaque école, fournir le nombre de réponses à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?' pour l’option 'Université Laval'.",
    "Pour l’année 2017, pour chaque école, compter le nombre de réponses à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?' pour l’option 'Université de Montréal'.",
    "Pour chaque école en 2013, agréger la répartition des réponses à la question 'Durant vos études postsecondaires, quelles seront vos sources de financement ?' en analysant l’option 'Autre'.",
    "Pour chaque école en 2013, pour la question sur les sources de financement durant les études postsecondaires, indiquer le nombre de réponses pour l’option 'Économie personnelle'.",
    "Pour chaque école en 2013, pour la question sur les sources de financement durant les études postsecondaires, compter le nombre de réponses pour l’option 'Contribution des parents'.",
    "Pour chaque école en 2013, pour la question sur les sources de financement durant les études postsecondaires, agréger le nombre de réponses pour l’option 'Travail à temps partiel'.",
    "Pour l’année 2012, pour chaque école, fournir la répartition des réponses à la question 'En général, êtes-vous satisfait/e de vos résultats scolaires ?' en se focalisant sur l’option 'Très satisfait/e'.",
    "Pour l’année 2012, pour chaque école, agréger le nombre de réponses 'Insatisfait/e' à la question 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'.",
    "Pour l’année 2012, pour chaque école, compter le nombre de réponses 'Non répondu' à la question 'En général, êtes-vous satisfait/e de vos résultats scolaires ?'.",
    "Pour l’année 2011, pour chaque école, calculer le taux de réponses à la question 'En général, vos cours sont de quel niveau scolaire ?' en mettant en avant l’option 'Régulier'.",
    "Pour l’année 2011, pour chaque école, agréger le nombre de réponses 'Adaptation scolaire' à la question 'En général, vos cours sont de quel niveau scolaire ?'.",
    "Pour l’année 2011, pour chaque école, fournir la distribution des réponses à la question 'En général, vos cours sont de quel niveau scolaire ?' en se focalisant sur l’option 'Compétences essentielles'.",
    "Pour l’année 2010, pour chaque école, analyser la répartition des réponses à la question 'Que prévoyez-vous faire en septembre prochain ?' en se concentrant sur l’option 'Formation professionnelle'.",
    "Pour l’année 2010, pour chaque école, compter le nombre de réponses 'Non répondu' à la question 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2010, pour chaque école, fournir le nombre de réponses indiquant 'Programmes jeunesse' dans la question 'Que prévoyez-vous faire en septembre prochain ?'.",
    "Pour l’année 2009, pour chaque école, agréger les réponses à la question 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire' pour l’option 'Sciences sociales'.",
    "Pour l’année 2009, pour chaque école, calculer le nombre de réponses pour l’option 'Sc. De l'environnement' dans la question 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2009, pour chaque école, agréger le nombre de réponses pour l’option 'Technologie' dans la question sur les cours préférés durant le secondaire.",
    "Pour l’année 2009, pour chaque école, fournir le nombre de réponses se concentrant sur l’option 'Droit' dans la question 'Indiquez les deux cours que vous avez les plus appréciés durant votre secondaire'.",
    "Pour l’année 2008, pour chaque école, analyser la répartition des réponses à la question 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?' en se focalisant sur l’option 'Très satisfait/e'.",
    "Pour l’année 2008, pour chaque école, agréger le nombre de réponses 'Insatisfait/e' à la question 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2008, pour chaque école, compter le nombre de réponses 'Non répondu' à la question 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?'.",
    "Pour l’année 2007, pour chaque école, fournir la répartition des réponses à la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?' en mettant en avant l’option 'Sciences sociales et disciplines connexes'.",
    "Pour l’année 2007, pour chaque école, agréger le nombre de réponses pour l’option 'Génie et sciences appliquées' dans la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?'.",
    "Pour l’année 2007, pour chaque école, analyser le nombre de réponses indiquant 'Sans spécialisation' dans la question sur le domaine d’études postsecondaires envisagé.",
    "Pour l’année 2006, pour chaque école, compter le nombre de réponses à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?' pour l’option 'Très important'.",
    "Pour l’année 2006, pour chaque école, agréger le nombre de réponses 'Pas du tout important' à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?'.",
    "Pour l’année 2006, pour chaque école, fournir le nombre de réponses 'Non répondu' à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?'.",
    "Pour l’année 2010, pour chaque école, compter le nombre de réponses 'Oui' à la question 'Seriez-vous intéressé/e à faire un retour aux études ?'.",
    "Pour l’année 2010, pour chaque école, agréger le nombre de réponses 'Non' à la question 'Seriez-vous intéressé/e à faire un retour aux études ?'.",
    "Pour l’année 2019, pour chaque école, analyser la répartition des réponses à la question 'Dans quel type d'institution avez-vous étudié ?' en se focalisant sur l’option 'Universitaire'.",
    "Pour l’année 2019, pour chaque école, fournir le nombre de réponses indiquant 'Collégial' à la question 'Dans quel type d'institution avez-vous étudié ?'"
    "Pour chaque école en 2018, quelle était la proportion d'étudiants qui prévoyaient poursuivre leurs études postsecondaires dans le domaine 'Commerce, gestion et administration des affaires' ?",
    "Comment a évolué la satisfaction des élèves concernant leurs relations avec le personnel de l'école à W.-A.-Losier entre 2010 et 2019 ?",
    "Pour l'année 2016, quelle est la répartition des réponses à la question 'Est-ce que le fait de terminer votre 12e année est important pour vous ?' pour chaque école ?",
    "Quelle école en 2017 présentait le plus grand pourcentage d'élèves ayant indiqué 'Mathématiques' comme l'un des cours les plus appréciés durant leur secondaire ?",
    "Comment a évolué la proportion d'étudiants ayant occupé un emploi rémunéré pendant l'année scolaire à l'école Marie-Esther entre 2004 et 2019 ?",
    "Pour l'année 2015, comparez entre les écoles la proportion d'élèves qui accepteraient une offre d'emploi dans la Péninsule acadienne après leurs études postsecondaires.",
    "Quel était le pourcentage d'étudiants de Louis-Mailloux en 2008 qui indiquaient être 'Très satisfait/e' de leurs résultats scolaires ?",
    "Comment a évolué le pourcentage d'étudiants prévoyant travailler 'Dans la Péninsule acadienne' après leurs études postsecondaires à l'école Centre La Fontaine entre 2004 et 2012 ?",
    "Pour l'année 2018, quelle école présentait la plus forte proportion d'étudiants indiquant 'Prêt étudiant' comme source de financement pour leurs études postsecondaires ?",
    "Comment a évolué le taux d'étudiants indiquant 'Marché du travail' comme prévision pour septembre prochain à l'école Roland-Pépin entre 2014 et 2019 ?",
    "Pour l'école Secondaire Népisiguit en 2016, quelle était la répartition des niveaux de résultats scolaires des étudiants ?",
    "Quelle était la proportion d'élèves de l'école W.-A.-Losier en 2011 qui considéraient leurs relations avec les autres élèves comme 'Très satisfait/e' ?",
    "Pour l'année 2007, comparez le pourcentage d'étudiants dont les cours étaient de niveau 'Régulier' entre les écoles Marie-Esther et Louis-Mailloux.",
    "Comment a évolué la proportion d'étudiants de l'école Aux quatre vents qui prévoyaient utiliser 'Ma propre voiture/motocyclette' comme moyen de transport durant leur première année d'études entre 2014 et 2019 ?",
    "Pour l'école Centre La Fontaine en 2010, quel était le pourcentage d'élèves qui indiquaient que les services d'orientation avaient 'Très bien' répondu à leurs besoins ?",
    "Quelle école en 2017 avait la plus forte proportion d'étudiants avec des résultats scolaires 'de 95 % à 100 %' ?",
    "Pour l'année 2019, quelle était la répartition des institutions postsecondaires que les élèves de Roland-Pépin pensaient fréquenter ?",
    "Comment a évolué la proportion d'étudiants indiquant 'Français' comme l'un des cours les plus appréciés à l'école Marie-Esther entre 2004 et 2019 ?",
    "Pour l'école Louis-Mailloux en 2012, quel était le pourcentage d'élèves qui ont indiqué 'Contribution des parents' comme source de financement pour leurs études postsecondaires ?",
    "Quelles écoles en 2018 présentaient le plus grand écart entre le nombre d'étudiants prévoyant aller sur le 'Marché du travail' et ceux prévoyant poursuivre des 'Études universitaires' ?",
    "Pour l'année 2006, quelle était la proportion d'étudiants de W.-A.-Losier qui avaient l'intention de s'établir dans la Péninsule acadienne au cours des cinq années suivantes ?",
    "Comment a évolué le pourcentage d'étudiants indiquant être intéressés à faire un retour aux études à l'école Centre La Fontaine entre 2004 et 2012 ?",
    "Pour l'école Marie-Esther en 2008, quelle était la répartition des réponses concernant le niveau d'éducation le plus élevé atteint ?",
    "Quelle école en 2011 présentait la plus forte proportion d'élèves cherchant un emploi dans le secteur 'Soins de santé et assistance sociale' ?",
    "Pour l'année 2019, comparez entre les écoles la proportion d'élèves qui considèrent que terminer leur 12e année est 'Très important' pour eux.",
    "Comment a évolué le taux d'étudiants disponibles pour travailler immédiatement à l'école Louis-Mailloux entre 2004 et 2012 ?",
    "Pour l'école Secondaire Népisiguit en 2015, quel était le pourcentage d'élèves indiquant 'Études universitaires' comme prévision pour septembre suivant ?",
    "Quelle était la répartition des domaines d'études postsecondaires choisis par les élèves de l'école Aux quatre vents en 2017 ?",
    "Pour l'année 2008, quelle école avait la plus forte proportion d'étudiants ayant travaillé 'Temps partiel fin de semaine' depuis septembre ?",
    "Comment a évolué la proportion d'étudiants de l'école W.-A.-Losier qui ont indiqué être en recherche d'emploi entre 2004 et 2012 ?",
    "Pour l'école Marie-Esther en 2010, quel pourcentage d'élèves avait accumulé '18 à 24 mois' d'expérience de travail au cours des deux années précédentes ?",
    "Quelle école en 2019 présentait le pourcentage le plus élevé d'étudiants satisfaits de leurs résultats scolaires ?",
    "Pour l'année 2007, comparez la raison principale pour laquelle les élèves n'avaient pas travaillé entre les écoles Centre La Fontaine et W.-A.-Losier.",
    "Comment a évolué le taux d'étudiants qui considéraient leur occupation principale comme 'Études universitaires' à l'école Louis-Mailloux entre 2004 et 2012 ?",
    "Pour l'école Roland-Pépin en 2016, quelle était la répartition des moyens de transport que les élèves prévoyaient utiliser pendant leur première année d'études ?",
    "Quelles écoles en 2018 avaient la plus forte proportion d'étudiants indiquant 'Ma propre voiture/motocyclette' comme moyen de transport prévu ?",
    "Pour l'année 2012, quel était le pourcentage d'élèves de Centre La Fontaine qui envisageaient de changer d'emploi dans l'année suivante ?",
    "Comment a évolué la proportion d'étudiants indiquant 'Beaux-arts et arts appliqués' comme domaine d'études postsecondaires à l'école Marie-Esther entre 2004 et 2019 ?",
    "Pour l'école W.-A.-Losier en 2005, quelle était la répartition des provinces ou pays où les étudiants avaient étudié ?",
    "Quelle école en 2014 présentait le plus grand écart entre les réponses 'Oui' et 'Non' à la question concernant l'acceptation d'une offre d'emploi dans la Péninsule acadienne ?",
    "Pour l'année 2011, comparez entre les écoles la proportion d'élèves ayant complété leurs études postsecondaires.",
    "Comment a évolué le pourcentage d'étudiants qui considéraient leurs relations avec les autres élèves comme 'Satisfait/e' à l'école Aux quatre vents entre 2014 et 2019 ?",
    "Pour l'école Secondaire Népisiguit en 2017, quelle était la répartition des réponses à la question sur la satisfaction concernant les relations avec le personnel de l'école ?",
    "Quelle était la proportion d'élèves de l'école Louis-Mailloux en 2010 qui étaient intéressés à recevoir de l'information concernant une expérience de travail dans leur communauté ?",
    "Pour l'année 2006, quelle école avait le plus fort pourcentage d'étudiants indiquant 'Alberta' comme province où ils aimeraient travailler ?",
    "Comment a évolué la répartition des réponses à la question sur l'état civil des étudiants de l'école Centre La Fontaine entre 2004 et 2012 ?",
    "Pour l'école Marie-Esther en 2007, quel était le nombre d'étudiants qui indiquaient 'Économie personnelle' comme source de financement pour leurs études postsecondaires ?",
    "Quelle école en 2019 présentait la plus faible proportion d'étudiants indiquant 'Très insatisfait/e' concernant leurs relations avec le personnel de l'école ?",
    "Pour l'année 2005, comparez la proportion d'étudiants disponibles pour travailler immédiatement entre les écoles W.-A.-Losier et Louis-Mailloux."
    "Pour l'année 2018, pour chaque école, fournir le nombre de réponses concernant chacune des sources de financement suivantes : « Prêt étudiant », « Bourses étudiantes », « Contribution des parents » et « Travail à temps partiel ».",
    "Quelle est l’évolution du taux de participation (percent_answered) aux questionnaires par école au fil des années ?",
    "Quelles écoles présentent le plus grand écart entre le nombre d’étudiants masculins et féminins et comment cet écart évolue-t-il au fil du temps ?",
    "Pour la question « Seriez-vous intéressé(e) à faire un retour aux études ? », quelle différence de réponses observe-t-on entre hommes et femmes selon les écoles ?",
    "Quelles questions affichent les plus grandes disparités de réponses entre les genres, et ces disparités sont-elles constantes dans chacune des écoles ?",
    "Pour l'année 2019, pour chaque école, combien d'élèves ont répondu « Satisfait/e » ou « Très satisfait/e » à la question « Sur le plan de vos relations avec les autres élèves, êtes-vous satisfait/e de votre séjour au secondaire ? »",
    "Quels sont les pourcentages de réponses « Oui » et « Non » à la question « À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ? » pour chaque école en 2015 ?",
    "Combien d'élèves de chaque école ont indiqué « Marché du travail » comme réponse à la question « Que prévoyez-vous faire en septembre prochain ? » en 2017 ?",
    "Quelle est la distribution des réponses à la question « Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ? » pour chaque école en 2016 ?",
    "Pour l'année 2014, combien d'élèves de chaque école ont répondu « Important » ou « Très important » à la question « Est-ce que le fait de terminer votre 12e année est important pour vous ? »",
    "Quelle est la répartition des réponses à la question « En général, quels sont vos résultats scolaires en 10e 11e et 12e année ? » pour chaque école en 2018 ?",
    "Pour l'année 2019, quel pourcentage d'élèves de chaque école ont répondu « Oui » à la question « Seriez-vous intéressé/e à faire un retour aux études ? »",
    "Combien d'élèves de chaque école ont répondu « Oui » à la question « Existe-t-il des obstacles qui vous empêchent de poursuivre des études ? » en 2015 ?",
    "Quelle est la proportion de réponses « Oui » à la question « Seriez-vous intéressé/e à recevoir de l'information pour vous aider dans la poursuite de vos études ? » pour chaque école en 2016 ?",
    "Pour chaque école, quel est le nombre de réponses à la question « Dans quelle province canadienne ou ailleurs avez-vous étudié ? » en 2017 ?",
    "Quelle est la distribution des réponses à la question « Dans quelle province canadienne ou autre pays travaillez-vous ? » pour chaque école en 2018 ?",
    "Combien d'élèves de chaque école ont répondu « Oui » à la question « Envisagez-vous de changer d'emploi dans la prochaine année ? » en 2019 ?",
    "Pour l'année 2016, quel est le nombre de réponses à la question « Quelle est la principale raison pour laquelle vous envisagez de changer d'emploi ? » pour chaque école ?",
    "Quelle est la répartition des réponses à la question « Dans quelle région de la province travaillez-vous ? » pour chaque école en 2017 ?",
    "Pour chaque école, quel est le nombre de réponses à la question « Dans quelle catégorie de profession ou métier travaillez-vous ? » en 2018 ?",
    "Combien d'élèves de chaque école ont répondu « Oui » à la question « Présentement êtes-vous en attente ou à la recherche d'emploi ? » en 2019 ?",
    "Quelle est la distribution des réponses à la question « Au cours des 2 dernières années, combien d'employeurs avez-vous eus ? » pour chaque école en 2016 ?",
    "Pour l'année 2017, quel est le nombre de réponses à la question « Au cours des deux dernières années, combien de mois d'expérience de travail avez-vous accumulés ? » pour chaque école ?",
    "Combien d'élèves de chaque école ont répondu « Moins de 6 mois » à la question « Depuis combien de temps êtes-vous sans emploi ? » en 2018 ?",
    "Quelle est la répartition des réponses à la question « Quelle est la principale raison pour laquelle vous n'avez pas travaillé durant cette période ? » pour chaque école en 2019 ?",
    "Pour chaque école, quel est le nombre de réponses « Oui » à la question « Seriez-vous intéressé/e par une expérience de travail dans votre communauté ? » en 2015 ?",
    "Combien d'élèves de chaque école ont répondu « Oui » à la question « Seriez-vous intéressé à recevoir des l'information concernant une expérience de travail dans votre communauté ? » en 2016 ?",
    "Quelle est la distribution des réponses à la question « Êtes-vous disponible pour travailler maintenant ? » pour chaque école en 2017 ?",
    "Pour l'année 2018, quel est le nombre de réponses à la question « Quel type d'emploi recherchez-vous ? » pour chaque école ?",
    "Quelle est la répartition des réponses à la question « Dans quelle province canadienne ou autre pays aimeriez-vous travailler ? » pour chaque école en 2019 ?",
    "Combien d'élèves de chaque école ont répondu « Nord-Est » à la question « Dans quelle région de la province aimeriez-vous travailler ? » en 2016 ?",
    "Pour chaque école, quel est le nombre de réponses « Oui » à la question « Avez-vous eu un emploi au cours des 2 dernières années ? » en 2017 ?"
    "Pour l'année 2018, pour chaque école, fournir le nombre de réponses pour chacune des sources de financement ('Prêt étudiant', 'Bourses étudiantes', 'Contribution des parents' et 'Travail à temps partiel').",
    "Pour l'année 2018, agrégé par école, calculer le taux de participation (percent_answered) aux questionnaires.",
    "Par école, comparer les réponses 'Très satisfait/e' et 'Très insatisfait/e' à la question 'Sur le plan de vos relations avec le personnel de l'école, êtes-vous satisfait/e de votre séjour au secondaire ?' pour l'année 2016.",
    "Pour la question 'Seriez-vous intéressé(e) à faire un retour aux études ?', fournir par école la proportion des réponses 'Oui', 'Non' et 'Non répondu' pour l'année 2017.",
    "Pour chaque école, analyser l'évolution des réponses à la question 'Indiquez dans quel domaine vous avez l'intention de poursuivre vos études postsecondaires ?' entre 2014 et 2019.",
    "Par école, pour l'année 2015, agrégation des réponses à la question 'En général, quels sont vos résultats scolaires en 10e, 11e et 12e année ?' en regroupant les tranches ('de 81 % à 94 %', 'de 66 % à 80 %', etc.).",
    "Pour l'année 2019, par école, agréger le nombre de réponses à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' en distinguant les réponses 'Très bien', 'Bien', 'Peu', et 'Pas du tout'.",
    "Pour chaque école, pour l'année 2018, fournir la répartition des réponses à la question 'Que prévoyez-vous faire en septembre prochain ?' en se focalisant sur les options 'Cégep', 'Études universitaires' et 'Formation professionnelle'.",
    "Pour l'année 2014, par école, évaluer la proportion de réponses 'Oui' et 'Non' à la question 'À la fin de vos études postsecondaires, si vous aviez une offre d'emploi dans la Péninsule acadienne, est-ce que vous l'accepteriez ?'.",
    "Par école, comparer la distribution des réponses 'Satisfait/e' et 'Non répondu' à la question 'En général, êtes-vous satisfait/e de vos résultats scolaires ?' pour l'année 2017.",
    "Pour l'année 2016, par école, agréger les réponses à la question 'Dans quelle province canadienne ou ailleurs avez-vous étudié ?' afin d'observer la répartition géographique des étudiants.",
    "Pour chaque école disposant d'un accès complet aux questionnaires (accès aux questions 1-52), calculer la variation annuelle du taux de réponses 'Non répondu' à la question 'Indiquez le nom de l'institution que vous pensez fréquenter l'an prochain ?' pour la période 2004 à 2019.",
    "Pour l'année 2019, par école, agréger les réponses à la question 'Quelle est la principale raison pour laquelle vous ne prévoyez pas poursuivre des études postsecondaires ?' afin d'identifier les obstacles prépondérants (par exemple, 'Accès au marché du travail', 'Manque d’intérêt pour les études', etc.).",
    "Pour l'année 2015, par école, calculer la distribution des réponses à la question 'Envisagez-vous de changer d'emploi dans la prochaine année ?' en distinguant clairement 'Oui' et 'Non'.",
    "Par école, pour l'année 2014, évaluer la répartition des réponses à la question 'Est-ce que les services d'orientation que vous avez utilisés ont répondu à vos besoins ?' en se concentrant sur la différence entre 'Très bien' et 'Bien'.",
]
