questions = [
    "Pour l'école Aux quatre vents en 2016, quel pourcentage d'élèves a choisi 'Français' comme l'un des deux cours les plus appréciés (question 16) ?",
    "Comment la proportion d'élèves 'Très insatisfait/e' de leurs relations avec les autres élèves (question 17) a-t-elle évolué pour Secondaire Népisiguit entre 2014 et 2019 ?",
    "En 2017, pour l'école Roland-Pépin, quelle était la part des élèves se déclarant 'Satisfait/e' de leurs relations avec le personnel de l'école (question 18) ?",
    "Comparer la proportion d'élèves prévoyant des 'Études collégiales' (question 19) en 2019 entre l'école Aux quatre vents et l'école Secondaire Népisiguit.",
    "Pour l'école W.-A.-Losier en 2014, quel était le domaine d'études postsecondaires (question 20) le plus fréquemment choisi ?",
    "Quelle est l'évolution du pourcentage d'élèves répondant 'Pas utilisés' aux services d'orientation (question 21) pour l'école Louis-Mailloux entre 2014 et 2019 ?",
    "En 2015, pour l'école Marie-Esther, quelle proportion d'élèves a répondu 'Je ne sais pas' concernant l'acceptation d'une offre d'emploi dans la Péninsule (question 22) ?",
    "Pour l'année 2008, quelle proportion des répondants du Centre La Fontaine prévoyait travailler 'Dans la Péninsule acadienne' après leurs études postsecondaires (question 23) ?",
    "En 2010, pour l'école Louis-Mailloux, quel pourcentage d'élèves pensait fréquenter l''Université de Moncton - campus Shippagan' (question 24) ?",
    "Comment la source de financement 'Contribution des parents' (question 25) a-t-elle varié pour les élèves de W.-A.-Losier entre 2014 et 2017 ?",
    "Pour l'école Marie-Esther en 2016, quel était le moyen de transport local le plus envisagé parmi 'Voiture de mes parents' et 'À pied' (question 26) ?",
    "En 2018, pour l'école Secondaire Népisiguit, la raison 'Manque d’intérêt pour les études/formation' (question 27) était-elle plus fréquente que 'Problèmes monétaires' pour ne pas poursuivre les études ?",
    "Quelle est l'évolution de l'emploi rémunéré 'Temps partiel à la semaine' (question 28) pour les élèves de l'école Roland-Pépin de 2014 à 2018 ?",
    "Comparer le pourcentage d'élèves jugeant l'obtention de la 12e année 'Important' (question 29) en 2019 entre Aux quatre vents et Roland-Pépin.",
    "En 2014, pour l'école Secondaire Népisiguit, quelle proportion d'élèves avait des résultats scolaires 'de 95 % à 100 %' (question 30) ?",
    "Comment la proportion d'élèves suivant des cours de niveau 'Régulier' (question 31) a-t-elle changé pour l'école Marie-Esther entre 2014 et 2019 ?",
    "Pour l'école W.-A.-Losier en 2015, quel pourcentage d'élèves était 'Très satisfait/e' de ses résultats scolaires (question 32) ?",
    "En 2004, pour les répondants de l'école Louis-Mailloux, quelle proportion demeurait hors Péninsule depuis 'moins d'un an' (question 45) ?",
    "Quelle était la raison principale ('Travail', 'Étude', 'Autre' - question 46) pour avoir quitté la Péninsule pour les répondants de Marie-Esther en 2010 ?",
    "Comment l'intention de s'établir dans la Péninsule ('Oui' vs 'Non' - question 47) a-t-elle évolué pour les répondants de W.-A.-Losier entre 2004 et 2012 ?",
    "En 2011, pour le Centre La Fontaine, quel pourcentage de répondants avait un niveau d'éducation 'Collégial' (question 48) ?",
    "Pour l'école Louis-Mailloux en 2005, quelle était la proportion de répondants dont l'occupation principale était 'Recherche d'emploi / Sans emploi' (question 49) ?",
    "Quelle est l'évolution de l'état civil 'Marié/e' ou 'Conjoint/e de fait' (question 50) parmi les répondants de Marie-Esther entre 2004 et 2012 ?",
    "En 2007, pour les répondants de W.-A.-Losier, quelle proportion était originaire de la localité 'Tracadie' (question 51) ?", # Note: Requires checking if 'Tracadie' is in the original long list. Assuming it is for example purposes.
    "Comparer le lieu de résidence actuel ('Péninsule acadienne' vs 'Ailleurs au N.-B.' - question 52) des répondants du Centre La Fontaine et de Louis-Mailloux en 2008.",
    "Pour l'école Marie-Esther en 2012, quelle province ('Québec', 'Nouveau-Brunswick' - question 1) était la plus citée comme lieu d'études ?",
    "En 2006, pour les répondants de W.-A.-Losier, la source de financement 'Économie personnelle' était-elle plus fréquente que 'Travail à temps partiel' (question 2) ?",
    "Quelle proportion des répondants du Centre La Fontaine en 2004 était 'Présentement aux études' quand on leur demandait s'ils étaient intéressés par un retour aux études (question 3) ?",
    "Pour l'école Louis-Mailloux en 2007, quelle proportion de répondants a indiqué 'Oui' à l'existence d'obstacles empêchant la poursuite des études (question 4) ?",
    "Comment l'intérêt ('Oui') pour recevoir de l'information sur la poursuite des études (question 5) a-t-il varié pour les répondants de Marie-Esther entre 2004 et 2010 ?",
    "En 2011, pour l'école W.-A.-Losier, la majorité des répondants étudiait-elle dans une institution 'Universitaire' (question 6) ?",
    "Quelle proportion des répondants du Centre La Fontaine en 2005 suivait un régime d'études 'Temps partiel' (question 7) ?",
    "En 2012, pour l'école Louis-Mailloux, quel était le niveau d'études le plus fréquent ('Premier cycle universitaire', 'Diplôme', etc. - question 8) ?",
    "Pour les répondants de Marie-Esther en 2007, quel était le domaine d'études le plus cité entre 'Lettres, sciences humaines' et 'Enseignement, loisirs et orientation' (question 9) ?",
    "Quelle est l'évolution du pourcentage de répondants n'ayant 'Non' complété leurs études (question 10) pour W.-A.-Losier entre 2004 et 2012 ?",
    "En 2008, pour les répondants du Centre La Fontaine, quelle proportion travaillait en 'Alberta' (question 11) ?",
    "Comment la proportion de répondants envisageant ('Oui') de changer d'emploi (question 12) a-t-elle évolué pour Louis-Mailloux entre 2004 et 2012 ?",
    "En 2005, pour Marie-Esther, la raison 'Je recherche la sécurité d'emploi' (question 13) était-elle souvent citée pour vouloir changer d'emploi ?",
    "Pour les répondants de W.-A.-Losier en 2011, quelle proportion travaillait dans la région 'Sud-Est' du Nouveau-Brunswick (question 14) ?",
    "Quelle était la catégorie de profession la plus fréquente ('Commerce de détail', 'Services publics', etc. - question 15) pour les répondants du Centre La Fontaine en 2006 ?",
    "En 2010, pour l'école Louis-Mailloux, quel pourcentage de répondants était en 'Attente d\'emploi' (question 33) ?",
    "Comparer le nombre d'employeurs ('Un' vs 'Deux') au cours des 2 dernières années (question 34) pour les répondants de Marie-Esther et W.-A.-Losier en 2007.",
    "Pour les répondants du Centre La Fontaine en 2012, quelle était la durée d'expérience de travail la plus fréquente ('6 à 12 mois' vs '18 à 24 mois' - question 35) ?",
    "Quelle est l'évolution de la proportion de répondants sans emploi depuis 'Moins de 6 mois' (question 36) pour Louis-Mailloux entre 2004 et 2012 ?",
    "En 2005, pour Marie-Esther, la raison 'Attente d'un rappel au travail' (question 37) était-elle une cause fréquente de non-travail ?",
    "Comparer l'intérêt ('Oui') pour une expérience de travail communautaire (question 38) entre les répondants de W.-A.-Losier et du Centre La Fontaine en 2008.",
    "En 2011, quelle proportion des répondants de Louis-Mailloux était intéressée ('Oui') à recevoir de l'information sur une expérience de travail communautaire (question 39) ?",
    "Comment la disponibilité immédiate pour travailler ('Oui' - question 40) a-t-elle évolué pour les répondants de Marie-Esther entre 2004 et 2012 ?",
    "Pour les répondants de W.-A.-Losier en 2006, quel était le type d'emploi le plus recherché entre 'Hébergement et services de restauration' et 'Administration publiques' (question 41) ?",
    "En 2010, quelle proportion des répondants du Centre La Fontaine souhaitait travailler au 'Québec' (question 42) ?",
    "Pour l'école Louis-Mailloux en 2005, quel pourcentage d'élèves a indiqué 'Très satisfait/e' concernant leurs relations avec les autres élèves (question 17)?",
    "Comment la proportion d'élèves prévoyant d'aller sur le 'Marché du travail' (question 19) a-t-elle évolué pour l'école Marie-Esther entre 2004 et 2008 ?",
    "En 2011, pour le Centre La Fontaine, quelle était la répartition des réponses à la question sur la satisfaction des services d'orientation (question 21) parmi 'Très bien', 'Bien' et 'Pas utilisés'?",
    "Pour l'année 2015, quelle proportion d'élèves de l'école W.-A.-Losier a répondu 'Oui' à la question sur l'acceptation d'une offre d'emploi dans la Péninsule acadienne (question 22) ?",
    "Quelles étaient les trois principales institutions postsecondaires (question 24) mentionnées par les élèves de l'école Louis-Mailloux en 2012 ?",
    "En 2018, pour l'école Aux quatre vents, quel pourcentage d'élèves a indiqué 'Prêt étudiant' comme source de financement (question 25) ?",
    "Comment le choix du moyen de transport 'Ma propre voiture/motocyclette' (question 26) a-t-il évolué pour les élèves de l'école Marie-Esther entre 2014 et 2019 ?",
    "Pour l'école W.-A.-Losier en 2009, quelle était la raison principale ('Accès au marché du travail', 'Manque d’intérêt', etc. - question 27) pour ne pas poursuivre d'études postsecondaires ?",
    "En 2016, pour l'école Secondaire Népisiguit, quel pourcentage d'élèves a déclaré occuper un emploi rémunéré 'Temps partiel fin de semaine' (question 28) ?",
    "Quelle est l'évolution de la proportion d'élèves jugeant 'Très important' de terminer leur 12e année (question 29) à l'école Roland-Pépin entre 2014 et 2019 ?",
    "Pour l'école Aux quatre vents en 2017, quelle était la répartition des résultats scolaires (question 30) entre 'de 81 % à 94 %' et 'de 66 % à 80 %'?",
    "Comment la satisfaction générale des résultats scolaires ('Satisfait/e' ou 'Très satisfait/e' - question 32) a-t-elle changé pour les élèves du Centre La Fontaine entre 2014 et 2019 ?",
    "Pour les répondants de l'école Marie-Esther en 2006, quel pourcentage demeurait à l'extérieur de la Péninsule acadienne depuis 'Plus de quatre' ans (question 45) ?",
    "En 2008, pour les répondants de l'école W.-A.-Losier ayant quitté la Péninsule, quelle proportion a indiqué 'Travail' comme raison (question 46) ?",
    "Quelle est la tendance de l'intention de s'établir dans la Péninsule acadienne ('Oui' - question 47) pour les répondants du Centre La Fontaine entre 2004 et 2012 ?",
    "Pour l'école Louis-Mailloux en 2007, quelle proportion des répondants a indiqué 'Universitaire (baccalauréat)' comme plus haut niveau d'éducation (question 48) ?",
    "En 2010, pour les répondants de l'école Marie-Esther, quelle était la principale occupation ('Marché du travail', 'Études universitaires', etc. - question 49) ?",
    "Comment la proportion de répondants se déclarant 'Célibataire' (question 50) a-t-elle évolué pour l'école W.-A.-Losier entre 2004 et 2012 ?",
    "Pour l'année 2005, quelle proportion des répondants du Centre La Fontaine demeurait 'Ailleurs au N.-B.' (question 52) ?",
    "En 2011, pour l'école Louis-Mailloux, quelle province canadienne ('Québec', 'Ontario', 'Nouveau-Brunswick' - question 1) était la plus mentionnée comme lieu d'études ?",
    "Pour les répondants de l'école Marie-Esther en 2006, quelles étaient les deux sources de financement ('Prêts étudiant', 'Contribution des parents', etc. - question 2) les plus fréquentes ?",
    "En 2008, quelle proportion des répondants de l'école W.-A.-Losier a répondu 'Oui' à l'intérêt pour un retour aux études (question 3) ?",
    "Pour le Centre La Fontaine en 2012, y avait-il plus de répondants 'Oui' ou 'Non' concernant les obstacles empêchant la poursuite des études (question 4) ?",
    "Comment l'intérêt à recevoir de l'information pour la poursuite des études ('Oui' - question 5) a-t-il évolué pour les répondants de Louis-Mailloux entre 2004 et 2012 ?",
    "En 2007, pour l'école Marie-Esther, la majorité des répondants étudiait-elle dans une institution 'Universitaire' ou 'Collégial' (question 6) ?",
    "Quelle était la proportion d'étudiants à 'Temps plein' versus 'Temps partiel' (question 7) pour l'école W.-A.-Losier en 2010 ?",
    "Pour les répondants du Centre La Fontaine en 2005, quel niveau d'études ('Premier cycle universitaire', 'Deuxième cycle', etc. - question 8) était le plus commun ?",
    "En 2011, pour l'école Louis-Mailloux, quel était le domaine d'études le plus fréquent parmi 'Commerce, gestion et administration des affaires' et 'Professions de la santé' (question 9) ?",
    "Quelle est l'évolution du taux de complétion des études ('Oui' - question 10) pour les répondants de l'école Marie-Esther entre 2004 et 2008 ?",
    "Pour l'école W.-A.-Losier en 2012, dans quelle province ('Nouveau-Brunswick', 'Québec', 'Alberta' - question 11) les répondants travaillaient-ils le plus souvent ?",
    "En 2006, pour les répondants du Centre La Fontaine, quel pourcentage envisageait de changer d'emploi ('Oui' - question 12) ?",
    "Pour l'école Louis-Mailloux en 2010, quelle était la principale raison ('Je veux travailler plus près de chez moi', 'Mon travail actuel ne correspond pas...' - question 13) pour envisager un changement d'emploi ?",
    "En 2004, pour les répondants de l'école Marie-Esther, la majorité travaillait-elle dans la région 'Nord-Est' du Nouveau-Brunswick (question 14) ?",
    "Comment la proportion de répondants travaillant dans le secteur 'Soins de santé et assistance sociale' (question 15) a-t-elle évolué pour l'école W.-A.-Losier entre 2004 et 2012 ?",
    "Pour les répondants du Centre La Fontaine en 2008, quelle proportion était en 'Recherche d\'emploi' (question 33) ?",
    "En 2011, pour l'école Louis-Mailloux, quel était le nombre d'employeurs ('Un', 'Deux', 'Plus de deux' - question 34) le plus fréquent au cours des 2 dernières années ?",
    "Quelle était la durée d'expérience de travail la plus fréquente ('Moins de 6 mois', '12 à 18 mois', etc. - question 35) pour les répondants de Marie-Esther en 2005 ?",
    "Pour l'école W.-A.-Losier en 2007, quelle proportion des répondants sans emploi l'était depuis 'Plus de 2 ans' (question 36) ?",
    "En 2010, pour les répondants sans emploi du Centre La Fontaine, quelle était la raison principale ('Chômage / travail saisonnier', 'Retour aux études', etc. - question 37) ?",
    "Quelle proportion des répondants de l'école Louis-Mailloux en 2012 était intéressée ('Oui') par une expérience de travail dans leur communauté (question 38) ?",
    "Comment l'intérêt à recevoir de l'information sur une expérience de travail ('Oui' - question 39) a-t-il changé pour les répondants de Marie-Esther entre 2004 et 2012 ?",
    "En 2004, pour l'école W.-A.-Losier, quel pourcentage de répondants était disponible pour travailler maintenant ('Oui' - question 40) ?",
    "Pour les répondants du Centre La Fontaine en 2011, quel type d'emploi ('Commerce de détail', 'Construction', etc. - question 41) était le plus recherché ?",
    "En 2008, pour l'école Louis-Mailloux, quelle province ('Nouveau-Brunswick', 'Alberta', 'Québec' - question 42) était la plus citée comme lieu de travail souhaité ?",
    "Quelle région de la province ('Nord-Est', 'Sud-Est', etc. - question 43) était la plus souhaitée pour travailler par les répondants de Marie-Esther en 2006 ?",
    "Pour les répondants de l'école W.-A.-Losier en 2005, quelle proportion a déclaré avoir eu un emploi au cours des 2 dernières années ('Oui' - question 44) ?",
    "Comparer la proportion d'élèves choisissant 'Études universitaires' comme projet postsecondaire (question 19) entre l'école Louis-Mailloux et l'école Marie-Esther en 2008.",
    "Pour l'année 2019, quelle école parmi Aux quatre vents, Secondaire Népisiguit et Roland-Pépin avait le plus haut pourcentage d'élèves satisfaits ('Satisfait/e' ou 'Très satisfait/e') de leurs résultats scolaires (question 32)?",
    "Analyser l'évolution de la réponse 'Je ne sais pas' à la question sur l'acceptation d'un emploi dans la Péninsule (question 22) pour l'école W.-A.-Losier entre 2014 et 2019.",
    "En 2010, pour les répondants du Centre La Fontaine, comparer la proportion de ceux dont la principale occupation était 'Études universitaires' versus 'Marché du travail' (question 49)."
]
